### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe2 in position 131: illegal multibyte sequence

### ISSUE THREAD

**Issue by fuyr** [teesec-research/tckit#1]
heybody,when i try to function the splitteeos.py that  console output the following error to me:

### INFO:__main__:Splitting TEEOS.img
Traceback (most recent call last):
  File "splitteeos.py", line 133, in <module>
    sys.exit(main(sys.argv[1]))
  File "splitteeos.py", line 117, in main
    return split(teeos_path)
  File "splitteeos.py", line 43, in split
    header_data = f.read(0x2000)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xe2 in position 131: illegal multibyte sequence

I know  it is an error when the internal code is converted to GBK code (default),so how do i solve the problem？
thanks very much

**Comment by UIT-20521672** [comment]
Im having the same issue. Mine looks like this.
It says: UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 129-130: invalid continuation byte
Please let me know if you have found the solution to this error.
![image](https://github.com/teesec-research/tckit/assets/91721050/ad4d7153-77df-44f3-84ae-f614cc3ddb26)

**Comment by bm16ton** [comment]
python v2 vs python v3?

I get by the split with v2 but globaltask2elf.py fails (with python2)
Traceback (most recent call last):
  File "../globaltask2elf.py", line 255, in <module>
    main()
  File "../globaltask2elf.py", line 251, in main
    build_elf(sys.argv[1])
  File "../globaltask2elf.py", line 104, in build_elf
    process_start    = sym_map['PROCESS_START']
KeyError: 'PROCESS_START'

and python3

Traceback (most recent call last):
  File "/ssd2/mate9-linux/newest-kernel-workings/tee-os/tckit/tas_out/../globaltask2elf.py", line 255, in <module>
    main()
  File "/ssd2/mate9-linux/newest-kernel-workings/tee-os/tckit/tas_out/../globaltask2elf.py", line 251, in main
    build_elf(sys.argv[1])
  File "/ssd2/mate9-linux/newest-kernel-workings/tee-os/tckit/tas_out/../globaltask2elf.py", line 69, in build_elf
    data = f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: invalid continuation byte
